### ISSUE TITLE
Diskussion zu wichtigen Funktionen 

### ISSUE THREAD

**Issue by Sumed22** [Sarvin23/Titanic#3]
Nach Aufgabe 3, sollen wir uns für sinvollen und notwendigen Funktionen entscheiden. Was glaubt ihr ?

**Comment by Goli2002** [comment]
Ich denke es hängt sehr von den Analysebedürfnissen ab, beziehungsweise was man genau erreichen möchte.

**Comment by Hutan92** [comment]
Ja, vorallem zwischen wievielen Variablen die Visualisierungen sein sollen, zum Beispiel bei den kategorialen Variablen.

**Comment by Sarvin23** [comment]
Es basiert auf unseren spezifischen Analysebedürfnissen aus, zum Beispiel  wenn man kategoriale Variablen mit numerische Variable analysieren moechte

**Comment by Sumed22** [comment]
Ja ich stimme dazu, da es nur wirklich eine dichotome Variable gibt, macht es für mich kein Sinn

**Comment by Goli2002** [comment]
Ja stimmt, plus man muss auch berücksichtigen, ob man hauptsächlich an kategorialen Variablen interessiert ist oder ob man keinen spezifischen Bedarf hat, die Korrelation zwischen einer kontinuierlichen und einer dichotomen Variablen zu analysieren.

**Comment by Hutan92** [comment]
hmmm stimmt, dann wäre: 
„calculate_bivariate_stats_correlation“  garnicht mehr soo wichtig oder?

**Comment by Sumed22** [comment]
Ja ganz genau. Dazu glaube ich das Visualisierung Funktion nicht wichtig ist, weil wenn man die anderen Funktionen kompilieren, kann man gut Absicht an der Beziehung zwischen verschiedene Variablen durch numerische Wert bekommen.

**Comment by Sumed22** [comment]
> hmmm stimmt, dann wäre: „calculate_bivariate_stats_correlation“ garnicht mehr soo wichtig oder?

jaa ich glaube so.

**Comment by Goli2002** [comment]
> hmmm stimmt, dann wäre: 
> 
> „calculate_bivariate_stats_correlation“  garnicht mehr soo wichtig oder?

Ja genau.

**Comment by Hutan92** [comment]
Hey Leute, Goltan und ich haben bei Aufgabe 4 einige Analysen und Visualisierungen durchgeführt und erstellt , habt ihr vielleicht noch eine Idee beziehungsweise Verbesserungsvorschläge?

**Comment by Goli2002** [comment]
Genau bei Aufgabe 5, könnt ihr noch weitere Ideen nennen, falls euch etwas einfällt.
